source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks! 

target 'MovieApp' do
	pod 'SwiftyJSON'
    pod 'SDWebImage'
    pod 'FloatRatingView'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
end
